spring:
  datasource:
    username: nm_0820
    password: Shl@0820
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.137.116:3306/nm?useUnicode=true&characterEncoding=utf8&useSSL=false
  activemq:
    broker-url: tcp://223.221.36.132:61616

logging:
  level:
    root: info
    org.apache.http: DEBUG
    com.soholy.cb: DEBUG


